'''
Created on 2017/10/16
script for data gather to EPW job.
using with phononSplit.py
woking on Linux machine, but not on Windows (maybe os.system problem)
@author: Emi Minamitani
'''
import os
import numpy as np
import argparse
import glob
import shutil

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description='phonon input ', fromfile_prefix_chars='@')
    parser.add_argument('--workingDir', metavar='root directory for inputs generated by phononSplit.py', default='./',action='store')
    parser.add_argument('--wfcClean', metavar='delete wfc file or not', type=bool, default='false', action='store')
    parser.add_argument('--prefix', metavar='prefix for QE calculation', type=str,action='store')
    
    args=parser.parse_args() 
    
    os.chdir(args.workingDir)
    try:
        os.mkdir('save')
    except OSError:
        print('directory already exist')
    
    try:
        os.mkdir('save/'+args.prefix+".phsave")
    except OSError:
        print('phsave directory already exist')
    
    fdir=open('directoryList.txt',"r")
    
    lines=fdir.readlines()
    
    print(lines)
    
    for i in lines:
        os.chdir(i.strip('\n'))
        
        start_q=0
        last_q=0
        
        fin=open(args.prefix+".phonon.in")
        inputLines=fin.readlines()
       
        
        for line in inputLines:
            if (line.find("start_q")>=0):
                start_q=int(line.strip("").strip("\n").split("=")[1])
            if (line.find("last_q")>=0):
                last_q=int(line.strip("").strip("\n").split("=")[1])
        
        
        print(start_q)
        print(last_q)
        
        #copy dyn file
        qpts=np.arange(start_q, last_q+1)
        for i in qpts:
            os.system('cp ' +args.prefix+'.dyn'+str(i) + ' ../save/'+ args.prefix+'.dyn_q'+str(i))
        
        
        #for copy the dvscf etc. need to switch Gamma point and other part
        if(start_q==1):
            qpts=np.arange(start_q+1, last_q+1)
        else:
            qpts=np.arange(start_q, last_q+1)
        
        print(qpts)
                    
        if (start_q==1):
            #special case for Gamma-point
            os.system('cp _ph0/'+args.prefix+'.dvscf1 ../save/'+args.prefix+'.dvscf_q1')
            os.system('cp _ph0/'+args.prefix+'.phsave/* ../save/'+args.prefix+'.phsave/')
        
        
        
        for i in qpts:
            os.system('cp _ph0/'+args.prefix+'.q_'+str(i)+'/'+args.prefix+'.dvscf1 ../save/'+args.prefix+'.dvscf_q'+str(i))
            os.system('cp _ph0/'+args.prefix+'.phsave/* ../save/'+args.prefix+'.phsave/')
            
            if(args.wfcClean):
                os.system('rm _ph0/'+args.prefix+'.q_'+str(i)+'/*wfc*' )
            
            
        
        os.chdir('../')
    